#!/bin/bash
echo "=== 队列不均匀问题分析 ==="
echo ""
echo "【问题现象】"
echo "1. 队列有时候空着"
echo "2. 突然就大几千图片"
echo "3. 一点也不均匀"
echo ""
echo "【可能原因分析】"
echo ""
echo "1. 扫描器批量发现大量图片"
echo "   - 扫描间隔：0.2秒"
echo "   - 如果扫描很慢（MinIO ListObjects耗时），可能在扫描期间积累了大量图片"
echo "   - 扫描完成后，一次性将所有新图片加入队列"
echo ""
echo "2. 图片标记时机问题"
echo "   - 图片在加入队列时立即标记为processed"
echo "   - 但如果队列满了，图片被丢弃，但已经标记为processed"
echo "   - 导致后续扫描不到这些图片，但MinIO中还有"
echo ""
echo "3. 推理速度跟不上抽帧速度"
echo "   - 抽帧速度快，推理速度慢"
echo "   - 队列持续积压"
echo "   - 扫描器继续扫描，发现更多图片"
echo ""
echo "4. 扫描器扫描所有图片，而不是增量扫描"
echo "   - 每次扫描都遍历所有MinIO对象"
echo "   - 如果MinIO中有大量图片，扫描会很慢"
echo "   - 扫描完成后，一次性发现大量新图片"
echo ""
echo "【代码逻辑分析】"
echo ""
echo "扫描器逻辑："
echo "1. 每0.2秒扫描一次MinIO"
echo "2. 遍历所有对象，检查是否已处理"
echo "3. 如果未处理，加入新图片列表"
echo "4. 一次性将所有新图片加入队列"
echo "5. 立即标记所有图片为已处理"
echo ""
echo "问题："
echo "- 如果MinIO中有1000张未处理图片，扫描器会一次性全部发现"
echo "- 然后一次性全部加入队列，导致队列突然变大"
echo "- 如果队列满了，图片被丢弃，但已标记为processed，导致后续扫描不到"
